### ISSUE TITLE
Multiple Signle Press button under 1 accessory for Stateless Switch

### ISSUE THREAD

**Issue by SimpleStufffff** [mpatfield/homebridge-easy-mqtt#127]
* **Please explain your feature request in a one or two sentences.**
in Mqttthing for each accessory set as stateless switch, I can add multiple single press button.

* **Is your feature request related to a problem? Please describe.**
Now I'm limited to 3 for each accessory, sing press, double press, and long press

* **Any particular devices that this relates to?**
RF remotes with multiple button

* **Anything else?**
Thank You!

**Comment by mpatfield** [comment]
@SimpleStufffff thanks for the ticket. This seems doable. I'll try to tackle it sometime next week.

**Comment by mpatfield** [comment]
When you get a chance, are you able to please share your existing MQTTThing config? That would help me make sure I don’t miss anything. Thanks!

**Comment by SimpleStufffff** [comment]
here are one of my MQTTThing config, 


            "accessory": "mqttthing",
            "type": "statelessProgrammableSwitch",
            "name": "Dinning Switch",
            "url": "192.168.0.5",
            "topics": {
                "getSwitch": [
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E08' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E0C' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E04' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E09' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E02' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E05' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E01' ) ? 1 : 0);"
                    },
                    {
                        "topic": "tele/rfbridge/RESULT",
                        "apply": "return( ( JSON.parse(message).RfReceived.Data == 'CA3E03' ) ? 1 : 0);"
                    }
                ]
            },
            "integerValue": true,
            "logMqtt": false,
            "restrictSwitchValues": [
                0
            ]
        },



so far I have try; 
                    "topicEventButtonPress": "tele/rfbridge/RESULT$.RfReceived.Data",
                    "valueSinglePress": [
                        "CA3E08",
                        "CA3E0C",
                        "CA3E04",
                        "CA3E09",
                        "CA3E02",
                        "CA3E05",
                        "CA3E01",
                        "CA3E03"
                    ]
and 
                    "topicEventButtonPress": "tele/rfbridge/RESULT$.RfReceived.Data",
                    "valueSinglePress": [
                        "CA3E08"
                    ],
                    "valueSinglePress": [
                        "CA3E0C"
                    ],
                    "valueSinglePress": [
                        "CA3E04"
                    ],
                    "valueSinglePress": [
                        "CA3E09"
                    ],
                    "valueSinglePress": [
                        "CA3E02"
                    ],
                    "valueSinglePress": [
                        "CA3E05"
                    ],
                    "valueSinglePress": [
                        "CA3E01"
                    ],
                    "valueSinglePress": [
                        "CA3E03"
                    ]

**Comment by mpatfield** [comment]
This is really helpful, thanks. I’ll definitely need to make some changes to support this but it should be pretty easy. I don’t have time this weekend but I can probably implement this early next week.

**Comment by SimpleStufffff** [comment]
Whenever you can, Thanks for the amazing work.

**Comment by mpatfield** [comment]
This has been implemented in `v1.5.4-beta.0`. I updated the documentation [here](https://github.com/mpatfield/homebridge-easy-mqtt/wiki/StatelessProgrammableSwitch).

Please check it out and let me know how it goes! Thanks for the feature request!

**Comment by SimpleStufffff** [comment]
after updating to v1.5.4-beta.0. 

I kept getting this error and loop 

TypeError: this.config.valueSinglePress?.split is not a function
    at StatelessButtonAccessory.get singlePressValues [as singlePressValues] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:124:63)
    at StatelessButtonAccessory.get isMultiButton [as isMultiButton] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:118:17)
    at StatelessButtonAccessory.getAccessoryType (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:149:17)
    at new MQTTAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/mqtt.ts:33:53)
    at new BaseAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/base.ts:18:5)
    at new ButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:31:5)
    at new StatelessButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/stateless.ts:6:7)
    at createAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/helper.ts:94:12)
    at HomebridgeEasyMQTT.setup (file:///homebridge/node_modules/homebridge-easy-mqtt/src/homebridge/platform.ts:109:25)

**Comment by mpatfield** [comment]
Can you share the config you are trying please?

**Comment by SimpleStufffff** [comment]
{
                    "info": {
                        "name": "Dinning Switch",
                        "type": "StatelessProgrammableSwitch"
                    },
                    "mqtt": {
                        "broker": "mqtt://192.168.0.5:1883"
                    },
                    "topicEventButtonPress": "tele/rfbridge/RESULT$.RfReceived.Data",
                    "valueSinglePress": [
                       "CA3E08"
                    ]
                }


this is the config, I didn't get a chance to edit the JSON config
the error occur right after updating to beta

**Comment by SimpleStufffff** [comment]
I try deleting everything, and start fresh. the error came back after adding just 1 accessory.

**Comment by SimpleStufffff** [comment]
[11/17/2025, 2:38:11 AM] [Easy MQTT] Restarting Process...
[11/17/2025, 2:38:12 AM] [Easy MQTT] Launched child bridge with PID 15460
[11/17/2025, 2:38:12 AM] Registering platform 'homebridge-easy-mqtt.HomebridgeEasyMQTT'
[11/17/2025, 2:38:12 AM] [Easy MQTT] Loaded homebridge-easy-mqtt v1.5.4-beta.0 child bridge successfully
[11/17/2025, 2:38:12 AM] Loaded 1 cached accessories from cachedAccessories.0ECA4EBE9D67.
[11/17/2025, 2:38:12 AM] [Easy MQTT] v1.5.4-beta.0 | System linux | Node v22.16.0 | HB v1.11.1 | HAPNodeJS v0.14.0
[11/17/2025, 2:38:12 AM] [Easy MQTT] Restoring Dinning Switch
[11/17/2025, 2:38:12 AM] Homebridge v1.11.1 (HAP v0.14.0) (EasyMQTT Switch) is running on port 49403.
TypeError: this.config.valueSinglePress?.split is not a function
    at StatelessButtonAccessory.get singlePressValues [as singlePressValues] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:124:63)
    at StatelessButtonAccessory.get isMultiButton [as isMultiButton] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:118:17)
    at StatelessButtonAccessory.getAccessoryType (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:149:17)
    at new MQTTAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/mqtt.ts:33:53)
    at new BaseAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/base.ts:18:5)
    at new ButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:31:5)
    at new StatelessButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/stateless.ts:6:7)
    at createAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/helper.ts:94:12)
    at HomebridgeEasyMQTT.setup (file:///homebridge/node_modules/homebridge-easy-mqtt/src/homebridge/platform.ts:109:25)
[11/17/2025, 2:38:12 AM] [Easy MQTT] Child bridge process ended
[11/17/2025, 2:38:12 AM] [Easy MQTT] Process Ended. Code: 1, Signal: null
[11/17/2025, 2:38:19 AM] [Easy MQTT] Restarting Process...
[11/17/2025, 2:38:20 AM] [Easy MQTT] Launched child bridge with PID 15489
[11/17/2025, 2:38:21 AM] Registering platform 'homebridge-easy-mqtt.HomebridgeEasyMQTT'
[11/17/2025, 2:38:21 AM] [Easy MQTT] Loaded homebridge-easy-mqtt v1.5.4-beta.0 child bridge successfully
[11/17/2025, 2:38:21 AM] Loaded 1 cached accessories from cachedAccessories.0ECA4EBE9D67.
[11/17/2025, 2:38:21 AM] [Easy MQTT] v1.5.4-beta.0 | System linux | Node v22.16.0 | HB v1.11.1 | HAPNodeJS v0.14.0
[11/17/2025, 2:38:21 AM] [Easy MQTT] Restoring Dinning Switch
[11/17/2025, 2:38:21 AM] Homebridge v1.11.1 (HAP v0.14.0) (EasyMQTT Switch) is running on port 49403.
TypeError: this.config.valueSinglePress?.split is not a function
    at StatelessButtonAccessory.get singlePressValues [as singlePressValues] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:124:63)
    at StatelessButtonAccessory.get isMultiButton [as isMultiButton] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:118:17)
    at StatelessButtonAccessory.getAccessoryType (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:149:17)
    at new MQTTAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/mqtt.ts:33:53)
    at new BaseAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/base.ts:18:5)
    at new ButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:31:5)
    at new StatelessButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/stateless.ts:6:7)
    at createAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/helper.ts:94:12)
    at HomebridgeEasyMQTT.setup (file:///homebridge/node_modules/homebridge-easy-mqtt/src/homebridge/platform.ts:109:25)
[11/17/2025, 2:38:21 AM] [Easy MQTT] Child bridge process ended
[11/17/2025, 2:38:21 AM] [Easy MQTT] Process Ended. Code: 1, Signal: null
[11/17/2025, 2:38:28 AM] [Easy MQTT] Restarting Process...
[11/17/2025, 2:38:29 AM] [Easy MQTT] Launched child bridge with PID 15522
[11/17/2025, 2:38:29 AM] [Homebridge UI] [homebridge-easy-mqtt] Incoming Request: i18n
[11/17/2025, 2:38:30 AM] Registering platform 'homebridge-easy-mqtt.HomebridgeEasyMQTT'
[11/17/2025, 2:38:30 AM] [Easy MQTT] Loaded homebridge-easy-mqtt v1.5.4-beta.0 child bridge successfully
[11/17/2025, 2:38:30 AM] Loaded 1 cached accessories from cachedAccessories.0ECA4EBE9D67.
[11/17/2025, 2:38:30 AM] [Easy MQTT] v1.5.4-beta.0 | System linux | Node v22.16.0 | HB v1.11.1 | HAPNodeJS v0.14.0
[11/17/2025, 2:38:30 AM] [Easy MQTT] Restoring Dinning Switch
[11/17/2025, 2:38:30 AM] Homebridge v1.11.1 (HAP v0.14.0) (EasyMQTT Switch) is running on port 49403.
TypeError: this.config.valueSinglePress?.split is not a function
    at StatelessButtonAccessory.get singlePressValues [as singlePressValues] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:124:63)
    at StatelessButtonAccessory.get isMultiButton [as isMultiButton] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:118:17)
    at StatelessButtonAccessory.getAccessoryType (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:149:17)
    at new MQTTAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/mqtt.ts:33:53)
    at new BaseAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/base.ts:18:5)
    at new ButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:31:5)
    at new StatelessButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/stateless.ts:6:7)
    at createAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/helper.ts:94:12)
    at HomebridgeEasyMQTT.setup (file:///homebridge/node_modules/homebridge-easy-mqtt/src/homebridge/platform.ts:109:25)
[11/17/2025, 2:38:30 AM] [Easy MQTT] Child bridge process ended
[11/17/2025, 2:38:30 AM] [Easy MQTT] Process Ended. Code: 1, Signal: null
[11/17/2025, 2:38:37 AM] [Easy MQTT] Restarting Process...
[11/17/2025, 2:38:38 AM] [Easy MQTT] Launched child bridge with PID 15547
[11/17/2025, 2:38:38 AM] Registering platform 'homebridge-easy-mqtt.HomebridgeEasyMQTT'
[11/17/2025, 2:38:38 AM] [Easy MQTT] Loaded homebridge-easy-mqtt v1.5.4-beta.0 child bridge successfully
[11/17/2025, 2:38:38 AM] Loaded 1 cached accessories from cachedAccessories.0ECA4EBE9D67.
[11/17/2025, 2:38:38 AM] [Easy MQTT] v1.5.4-beta.0 | System linux | Node v22.16.0 | HB v1.11.1 | HAPNodeJS v0.14.0
[11/17/2025, 2:38:38 AM] [Easy MQTT] Restoring Dinning Switch
[11/17/2025, 2:38:38 AM] Homebridge v1.11.1 (HAP v0.14.0) (EasyMQTT Switch) is running on port 49403.
[11/17/2025, 2:38:39 AM] [Homebridge UI] Running command /opt/homebridge/lib/node_modules/homebridge-config-ui-x/scripts/upgrade-install-plugin.sh homebridge-easy-mqtt 1.5.3 /var/lib/homebridge/node_modules.
TypeError: this.config.valueSinglePress?.split is not a function
    at StatelessButtonAccessory.get singlePressValues [as singlePressValues] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:124:63)
    at StatelessButtonAccessory.get isMultiButton [as isMultiButton] (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:118:17)
    at StatelessButtonAccessory.getAccessoryType (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:149:17)
    at new MQTTAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/mqtt.ts:33:53)
    at new BaseAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/base.ts:18:5)
    at new ButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/button.ts:31:5)
    at new StatelessButtonAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/button/stateless.ts:6:7)
    at createAccessory (file:///homebridge/node_modules/homebridge-easy-mqtt/src/accessory/abstract/helper.ts:94:12)
    at HomebridgeEasyMQTT.setup (file:///homebridge/node_modules/homebridge-easy-mqtt/src/homebridge/platform.ts:109:25)
[11/17/2025, 2:38:39 AM] [Easy MQTT] Child bridge process ended
[11/17/2025, 2:38:39 AM] [Easy MQTT] Process Ended. Code: 1, Signal: null

**Comment by mpatfield** [comment]
Ah, the reason it’s crashing is `valueSinglePress` expects a string.

`"valueSinglePress": "CA3E08"`

I considered changing it to an array but that made the config UI really complicated.

For multiple values, you will comma separate like this.

`"valueSinglePress": "CA3E08,CA3E0C,CA3E04"`

**Comment by SimpleStufffff** [comment]
Problem solved! I remove  the square brackets for array, and its working without any issue. Can't believe I missed that. 
Now I can completely migrate from MQTTThing. Thank You!

**Comment by SimpleStufffff** [comment]
is it possible to hide the Ignoring message and only show the actual button pressed event. Thanks again

[11/17/2025, 7:52:45 PM] [Easy MQTT] Gaming Room Remote was single pressed (E48C42)
[11/17/2025, 7:52:45 PM] [Easy MQTT] Dinning Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Pantry Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Tea Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Bedroom Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Kitchen Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Breakfast Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Hallway Switch unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] 10 Button Remote unable to determine button press event from value 'E48C42'. Ignoring…
[11/17/2025, 7:52:45 PM] [Easy MQTT] Blue Switch unable to determine button press event from value 'E48C42'. Ignoring…

**Comment by mpatfield** [comment]
Yeah, that's fair. Those messages should probably only show if `verbose` is true. I've suppressed them in `v1.5.4-beta.1`.
